config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :markets, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @facade = MarketsFacade.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<center><h1>Markets</h1></center>


  <%@facade.markets.each do |market|%>
  <section class="markets">
    <p class="name">Name: <%=market.name%></p>
    <p class="city">City: <%=market.city%></p>
    <p class="state">State: <%=market.state%></p>
    <p class="more_info"><%=button_to "More Info", market_path(market.id)%></p>
  </section>
  <%end%>